"""create service tables

Revision ID: 89a905bdebef
Revises: 
Create Date: 2024-08-27 22:27:04.466340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89a905bdebef"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("expire_date", sa.DATE(), nullable=True),
        sa.Column("prod_date", sa.DATE(), nullable=True),
        sa.Column("available_quantity", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True, default=False),
        sa.Column("coffee_shop_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_item_coffee_shop_id"),
        "inventory_item",
        ["coffee_shop_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_item_coffee_shop_id"), table_name="inventory_item")
    op.drop_table("inventory_item")
    # ### end Alembic commands ###
